### ISSUE TITLE
Valgrind warns of invalid read in map_hash_1

### ISSUE THREAD

**Issue by satukoskinen** [juliuskoskela/core#33]
```
==689== Memcheck, a memory error detector
==689== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==689== Using Valgrind-3.18.0.GIT-lbmacos and LibVEX; rerun with -h for copyright info
==689== Command: ./lem-in
==689== Parent PID: 82919
==689== 
--689-- run: /usr/bin/dsymutil "./lem-in"
==689== Invalid read of size 8
==689==    at 0x10000690C: map_hash_1 (map_hash_1.c:38)
==689==    by 0x100006485: map_get (map_get.c:18)
==689==    by 0x100001E84: lem_parse_link (lem_parse_link.c:20)
==689==    by 0x100001BB3: lem_parse_room (lem_parse_room.c:61)
==689==    by 0x100001A09: lem_parse_line (lem_parse_line.c:51)
==689==    by 0x1000017C0: lem_parse_input (lem_parse_input.c:63)
==689==    by 0x100001093: main (main.c:62)
==689==  Address 0x1016d7355 is 5 bytes inside a block of size 10 alloc'd
==689==    at 0x1000E2995: malloc (in /Users/skoskine/.brew/Cellar/valgrind/HEAD-eec4cf7/libexec/valgrind/vgpreload_memcheck-amd64-darwin.so)
==689==    by 0x10000841C: s_cdup (in ./lem-in)
==689==    by 0x1000088F4: s_readline (in ./lem-in)
==689==    by 0x10000192A: lem_parse_line (lem_parse_line.c:39)
==689==    by 0x1000017C0: lem_parse_input (lem_parse_input.c:63)
==689==    by 0x100001093: main (main.c:62)
==689== 
==689== Invalid read of size 8
==689==    at 0x10000690C: map_hash_1 (map_hash_1.c:38)
==689==    by 0x100006485: map_get (map_get.c:18)
==689==    by 0x100001E84: lem_parse_link (lem_parse_link.c:20)
==689==    by 0x1000019F0: lem_parse_line (lem_parse_line.c:49)
==689==    by 0x1000017C0: lem_parse_input (lem_parse_input.c:63)
==689==    by 0x100001093: main (main.c:62)
==689==  Address 0x1016d7895 is 5 bytes inside a block of size 10 alloc'd
==689==    at 0x1000E2995: malloc (in /Users/skoskine/.brew/Cellar/valgrind/HEAD-eec4cf7/libexec/valgrind/vgpreload_memcheck-amd64-darwin.so)
==689==    by 0x10000841C: s_cdup (in ./lem-in)
==689==    by 0x1000088F4: s_readline (in ./lem-in)
==689==    by 0x10000192A: lem_parse_line (lem_parse_line.c:39)
==689==    by 0x1000017C0: lem_parse_input (lem_parse_input.c:63)
==689==    by 0x100001093: main (main.c:62)
```

with the call ``valgrind --leak-check=full --log-file=file ./lem-in < test/generator_maps/gen_superposition_4``

**Comment by satukoskinen** [comment]
Adding the -fsanitize=address flag produces the following:

```
➜  lem_in git:(modify_node_attributes) ✗ ./lem-in < test/subject_maps/test_input_subject_3
=================================================================
==30537==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000107100530 at pc 0x000102aff744 bp 0x00016d312be0 sp 0x00016d312bd8
READ of size 8 at 0x000107100530 thread T0
    #0 0x102aff740 in map_hash_1 map_hash_1.c:38
    #1 0x102afe024 in map_add map_add.c:38
    #2 0x102afc49c in graph_add_node graph_add_node.c:29
    #3 0x102aeee90 in lem_parse_room lem_parse_room.c:69
    #4 0x102aee728 in lem_parse_line lem_parse_line.c:51
    #5 0x102aeddb8 in lem_parse_input lem_parse_input.c:56
    #6 0x102aed5c0 in main main.c:57
    #7 0x193dadf30 in start+0x0 (libdyld.dylib:arm64e+0x16f30)

0x000107100532 is located 0 bytes to the right of 2-byte region [0x000107100530,0x000107100532)
allocated by thread T0 here:
    #0 0x102e371c8 in wrap_malloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x3f1c8)
    #1 0x102b0767c in s_sub s_sub.c:23
    #2 0x102aeed98 in lem_parse_room lem_parse_room.c:67
    #3 0x102aee728 in lem_parse_line lem_parse_line.c:51
    #4 0x102aeddb8 in lem_parse_input lem_parse_input.c:56
    #5 0x102aed5c0 in main main.c:57
    #6 0x193dadf30 in start+0x0 (libdyld.dylib:arm64e+0x16f30)

SUMMARY: AddressSanitizer: heap-buffer-overflow map_hash_1.c:38 in map_hash_1
Shadow bytes around the buggy address:
  0x007020e40050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007020e40060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007020e40070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007020e40080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007020e40090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 fa
=>0x007020e400a0: fa fa 00 fa fa fa[02]fa fa fa 02 fa fa fa 06 fa
  0x007020e400b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020e400c0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 02 fa
  0x007020e400d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 00 fa
  0x007020e400e0: fa fa 00 fa fa fa 00 06 fa fa 00 00 fa fa 00 fa
  0x007020e400f0: fa fa 00 00 fa fa fd fd fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==30537==ABORTING
[1]    30537 abort      ./lem-in < test/subject_maps/test_input_subject_3
```

**Comment by juliuskoskela** [comment]
This bug has been recpnciled. relevant piece of code:

```c
else
{
	mcpy(&ndhead, str, wrdlen);
	hash64 = (hash64 ^ shift(ndhead, (8 - wrdlen) << 3)) * prime;
}
```
