### ISSUE TITLE
Address sanitizer problem with map

### ISSUE THREAD

**Issue by juliuskoskela** [juliuskoskela/core#5]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==687826==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55aa3c0e0978 bp 0x7ffdf7ddf6e0 sp 0x7ffdf7ddf688 T0)
==687826==The signal is caused by a READ memory access.
==687826==Hint: address points to the zero page.
    #0 0x55aa3c0e0977 in s_cmp (/home/julius/Repos/core/a.out+0x4977)
    #1 0x55aa3c0e011a in map_add (/home/julius/Repos/core/a.out+0x411a)
    #2 0x55aa3c0df52d in graph_add_node src/graph_add_node.c:16
    #3 0x55aa3c0de81c in main tests/test_graph_usage.c:73
    #4 0x7fc4d69000b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #5 0x55aa3c0de2cd in _start (/home/julius/Repos/core/a.out+0x22cd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/julius/Repos/core/a.out+0x4977) in s_cmp
==687826==ABORTING

**Comment by juliuskoskela** [comment]
Node wasn't properly copied during resize.
